 
# rule identifiers to exclude from running
# disabled_rules:
 
 # paths to ignore during linting. Takes precedence over `included`.
excluded:
 - Carthage
 - Pods
 - .build/
 - DerivedData/

line_length:
    warning: 110
    error: 130

file_length:
    warning: 350
    error: 400

type_body_length:
    warning: 300
    error: 350
    
opt_in_rules:
 - multiple_closures_with_trailing_closure
 - trailing_whitespace
 - anyobject_protocol
 - array_init
 - closure_end_indentation
 - closure_spacing
 - contains_over_filter_count
 - contains_over_first_not_nil
 - deployment_target
 - discouraged_object_literal
 - empty_collection_literal
 - empty_count
 - empty_string
 - explicit_self
 - file_types_order
 - first_where
 - force_unwrapping #error shavad
 - function_default_parameter_at_end
 - implicitly_unwrapped_optional
 - last_where
 - lower_acl_than_parent
 - multiline_function_chains
 - operator_usage_whitespace
 - overridden_super_call
 - private_action
 - private_outlet
 - reduce_into
 - redundant_type_annotation
 - sorted_first_last
 - strict_fileprivate
 - toggle_bool
 - type_contents_order
 - unneeded_parentheses_in_closure_argument
 - unowned_variable_capture
 - unused_declaration
 - unused_import
 - vertical_parameter_alignment_on_call
 - vertical_whitespace_between_cases
 - vertical_whitespace_closing_braces
 - yoda_condition

type_contents_order:
    order:
        - case
        - type_alias
        - associated_type
        - ib_outlet
        - type_property
        - instance_property
        - ib_inspectable
        - initializer
        - deinitializer
        - view_life_cycle_method
        - type_method
        - other_method
        - ib_action
        - subtype
        - subscript

identifier_name:
    min_length: 2
    excluded: [id, vc, x, y, to]

# Code Snppiet
#// MARK: - Constants
#// MARK: - Logical Variables
#// MARK: - UI Variables: we should declare property name completely for example: continueButton
#// MARK: - View Lifecycles
#// MARK: - Binders: for gestures and notifications
#// MARK: - Validation Checks
#// MARK: - UI Configurations
#// MARK: - Functions
#// MARK: - Localization
#// MARK: - Targets: for @objc selectors

#// MARK: - Setup: add SetupView() in BaseViewController



